name: ok
description: Hello Fun!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.20.0 <3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # 苹果图标
  flutter_svg: ^2.0.4 # 矢量图加载
  marquee: ^2.2.3 # 滚动字幕
  cached_network_image: ^3.2.3 # 网络图片缓存
  carousel_slider: ^4.2.1 # 图片轮播
  http: ^1.1.0 # HTTP请求
  flutter_staggered_grid_view: ^0.7.0 # 瀑布流布局



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/icon/
